# Setup
title:               Shobhit Asai
tagline:             'Product Manager and tinkerer'
description:         'I make digital products that solve a problem and delight users, social impact is a plus!'
url:                 https://asaiat.in
baseurl:             '' 
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Shobhit asai
  url:               https://twitter.com/asaiatin
  email:             asaiatin@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
